// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.01.2025, 13:19:37
const configMerger = require("D:/eori-main-main/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/eori-main-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/plugins/**/*.{js,ts,mjs}","D:/eori-main-main/composables/**/*.{js,ts,mjs}","D:/eori-main-main/utils/**/*.{js,ts,mjs}","D:/eori-main-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/eori-main-main/app.config.{js,ts,mjs}"] }));

module.exports = config
